### ISSUE TITLE
Further limit iam policies

### ISSUE THREAD

**Issue by tobstarr** [alex/letsencrypt-aws#97]
Any idea if it is possible to further limit the power of the iam policy document to only allow changes on TXT records for DNS challenges? I did not find anything in the AWS documentation and tried this

    `"Condition": {"StringEquals": {"route53:type": "TXT"}}` 

but it did not work out (no changes were allowed).

**Comment by kachkaev** [comment]
Hi @tobstarr have you managed to make an IAM role that only has access to writing TXT records. Also curious how this could be done – ended up here from google :–)

**Comment by tobstarr** [comment]
@kachkaev nope, we migrated to kubernetes and are using kube-lego which uses http challenges.

**Comment by kachkaev** [comment]
OK. I'm also trying to get letsencypt in k8s environment with traefik as a proxy server, I just think DNS challenges are somewhat better than the http ones since they allow for non-globally visible hosts. [The policies in this repo's README](https://github.com/alex/letsencrypt-aws#iam-policy) do give a hint, but they look a bit too sparse.
